blank_issues_enabled: false
contact_links:
  - name: Discuss posts
    url: https://github.com/michaeltlombardi/mikeywrites.fyi/discussions/categories/posts
    about: If you want to discuss a specific post, look for it in the linked discussions.
  - name: Ask a question
    url: https://github.com/michaeltlombardi/mikeywrites.fyi/discussions/categories/q-a
    about: If you'd like to ask me or other readers a question, do so in GitHub discussions.
  - name: Start a conversation
    url: https://github.com/michaeltlombardi/mikeywrites.fyi/discussions/categories/chat
    about: You can also start a general conversation in GitHub discussions.
  - name: Check news from Mikey
    url: https://github.com/michaeltlombardi/mikeywrites.fyi/discussions/categories/tidings
    about: I occasionally post news that doesn't make sense as a blog post in GitHub discussions.
